apiVersion: v1 
kind: Secret 
metadata: 
  name: rabbitmq 
  namespace: roboshop 
  labels: 
    project: roboshop 
    component: rabbitmq 
    tier: db 
data: 
  RABBITMQ_DEFAULT_USER: "cm9ib3Nob3AK"
  RABBITMQ_DEFAULT_PASS: "cm9ib3Nob3AxMjMK"

--- 

apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: rabbitmq 
  namespace: roboshop 
  labels: 
    project: roboshop 
    component: rabbitmq 
    tier: db 
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      project: roboshop 
      component: rabbitmq 
      tier: db
  template: 
      metadata: 
        labels: 
          project: roboshop 
          component: rabbitmq 
          tier: db
      spec: 
        containers: 
        - name: rabbitmq 
          image: vijaykammari/rabbitmq:v1 
          imagePullPolicy: Always
          envFrom:
          - secretRef: 
              name: rabbitmq

--- 

apiVersion: v1 
kind: Service 
metadata: 
  name: rabbitmq 
  namespace: roboshop
spec: 
  selector: 
    project: roboshop 
    component: rabbitmq 
    tier: db
  ports: 
  - protocol: TCP 
    port: 5672
    targetPort: 5672