apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim-static
spec:
  volumeName: static-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

# https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/examples/kubernetes/static-provisioning/manifests/claim.yaml