apiVersion: v1
kind: ConfigMap
metadata:
  name: mysqlc
  namespace: roboshop
data:
  MYSQL_ROOT_PASSWORD: "RoboShop@1"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: roboshop
data:
  my.cnf: |
    [mysqld]
    innodb_redo_log_capacity = 2G

---

# apiVersion: v1
# kind: Secret
# metadata:
#   name: mysql
#   namespace: roboshop
# data:
#   MYSQL_ROOT_PASSWORD: "Um9ib1Nob3BAMQ=="

---

apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    component: mysql
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: mysql
      tier: db
  template:
    metadata:
      labels:
        project: roboshop
        component: mysql
        tier: db
    spec:
      containers:
        - name: mysql
          image: vijaykammari/mysql:v1
          envFrom:
          - configMapRef:
              name: mysqlc
          imagePullPolicy: Always
          # livenessProbe:
          #   tcpSocket:
          #     port: 3306
          #   initialDelaySeconds: 20
          #   periodSeconds: 5
          #   timeoutSeconds: 3
          #   failureThreshold: 1
          # readinessProbe:
          #   tcpSocket:
          #     port: 3306
          #   initialDelaySeconds: 25
          #   periodSeconds: 5
          #   failureThreshold: 1
          volumeMounts:
          - name: mysql-config
            mountPath: /etc/mysql/conf.d/my.cnf 
            subPath: my.cnf
          volumeMounts:
          - name: cache-volume
            mountPath: /var/lib/mysql/
      volumes:
        - name: mysql-config
          configMap:
            name: mysql
      volumes:
      - name: cache-volume
        emptyDir:
          sizeLimit: 2Gi

---

apiVersion: v1 
kind: Service
metadata:
  name: mysql
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: mysql
    tier: db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306

