apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: roboshopcluster
  region: us-east-1
managedNodeGroups:
  - name: cluster1
    instanceTypes: ["t3.large"]
    desiredCapacity: 3 # by default it is 3
    spot: true # to create the spot instances


# it will take approx 15 minutes to create the cluster
# eksctl create cluster --config-file=01-cluster-creation.yml command to create the cluster
# eksctl delete cluster --config-file=01-cluster-creation.yml command to delete the cluster
