apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels: 
    environment: dev
    project: roboshop

# kubectl apply -f 02-namespace.yml
# kubectl delete -f 02-namespace.yml

# kubectl create namespace roboshop
# kubectl delete namespace roboshop