apiVersion: v1
kind: pods
metadata:
  name: frontend_pod
  namespace: dev
  labels:
    environment: dev
    project: roboshop
spec:
  containers:
    - name: nginx
      image: nginx

# kubectl apply -f 03.pod.yml
# kubectl get pods -n <namespace>
# kubectl get pods shows the default namespace pods
# kubectl describe pod <pod_name> shows the errors , and to which node it is running etc



