apiVersion: v1 
kind: Pod
metadata:
  name: podding 
  annotations:
    jenkins.url: "https://vijay/vijay/vijay"
    timestamp: "2026-08-04"
spec:
  containers:
    - name: nginx
      image: nginx
      env: 
        - name: COURSE
          value: DEVOPS
        - name: ENV 
          value: develop
