
#clusterIP service , If you don't mention any type by default it will create ClusterIP
# ClusterIP service is used for the pod-to-pod communication

apiVersion: v1
kind: Service
metadata:
  name: frontendservice
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: frontendpod
  ports:
    - protocol: TCP
      port: 80  # service port 

--- 

apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: roboshop
  labels:
    project: roboshop
    component: frontendpod
spec:
  containers:
  - name: nginx
    image: nginx

# Here while creating the pod it will check the service that having any selectors matching to my labels
# then it register its ip to the service
# we can verify the endpoints by describing the svc
