apiVersion: v1
kind: Service
metadata:
  name: frontendservice1
  namespace: roboshop
spec:
  type: NodePort
  selector:
    project: roboshop
    component: frontendpod1
  ports:
    - protocol: TCP
      port: 80  #serviceport
      targetPort: 80 #pod port

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx1
  namespace: roboshop
  labels:
    project: roboshop
    component: frontendpod1
spec:
  containers:
  - name: nginx
    image: nginx
