apiVersion: v1
kind: Service
metadata:
  name: frontendservice2
  namespace: roboshop
spec:
  type: LoadBalancer
  selector:
    project: roboshop
    component: frontendpod2
  ports:
    - protocol: TCP
      port: 80 # lb port and service port 
      targetPort: 80 #pod port

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  namespace: roboshop
  labels:
    project: roboshop
    component: frontendpod2
spec:
  containers:
  - name: nginx
    image: nginx