apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap1
  namespace: roboshop
data:
  name: "vijay"
  learning: "DevOps"

---

apiVersion: v1
kind: Pod 
metadata:
  name: nginx-pod
  namespace: roboshop
spec:
  containers:
  - name: frontend
    image: nginx
    envFrom:
    - configMapRef:
        name: configmap1
