apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  # here we used opaque to so that while putting the value it will decode and put
data:
  password: "dmlqYXkK"



---

apiVersion: v1
kind: Pod 
metadata: 
  name: secretpod
  namespace: roboshop
spec:
  containers:
  - name: nginx-pod2
    image: nginx
    envFrom:
    - secretRef:
        name: mysecret
