apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: roboshop
data:
  password: "dmlqYXkK"


---

apiVersion: v1
kind: Pod 
metadata: 
  name: secretpod
  namespace: roboshop
spec:
  containers:
  - name: nginx-pod2
    image: nginx
    envFrom:
    - secretRef:
        name: mysecret
