apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim-dynamic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 4Gi

# storageclass will create the 4GB of the ebs 