apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: Redis-deployment
  namespace: roboshop
  labels: 
    project: roboshop
    component: redis 
    tier: db 
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      project: roboshop
      component: redis 
      tier: db
  template: 
    metadata: 
      labels: 
        project: roboshop
        component: redis 
        tier: db
    spec: 
      containers: 
      - name: redis 
        image: vijaykammari/redis:v1
        imagePullPolicy: Always

--- 

apiVersion: v1 
kind: Service 
metadata:
  name: redis
  namespace: roboshop
  labels: 
    project: roboshop
    component: redis 
    tier: db
spec: 
  selector: 
    project: roboshop
    component: redis 
    tier: db
  ports: 
  - protocol: TCP 
    port: 6379
    targetPort: 6379