apiVersion: v1 
kind: ConfigMap
metadata: 
  name: cart 
  namespace: roboshop 
data: 
  REDIS_HOST: "redis" 
  CATALOGUE_HOST: "catalogue"
  CATALOGUE_PORT: "8080"
  
---

apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: cart
  namespace: roboshop
  labels: 
    project: roboshop
    component: cart 
    tier: application 
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      project: roboshop
      component: cart 
      tier: application
  template: 
    metadata: 
      labels: 
        project: roboshop
        component: cart 
        tier: application
    spec: 
      containers: 
      - name: cart 
        image: vijaykammari/cart:v1
        imagePullPolicy: Always
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 11
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 1
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 1
        envFrom: 
        - configMapRef: 
            name: cart

--- 

apiVersion: v1 
kind: Service 
metadata:
  name: cart
  namespace: roboshop
spec: 
  selector: 
    project: roboshop
    component: cart 
    tier: application
  ports: 
  - protocol: TCP 
    port: 8080
    targetPort: 8080

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cart-hpa
  namespace: roboshop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cart
  minReplicas: 1
  maxReplicas: 5 #70 in the real projects
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 5